$activeBorderColor = rgb(C1121F)
$inactiveBorderColor = rgb(202020)

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
}
